let texto = prompt(`Digite um valor`)
let num = Number(prompt(`Digite o mesmo valor`))

console.log(typeof(texto))
console.log(typeof(num))

if (texto == num){
    console.log(texto + num)
}

if(texto === num){
    console.log(`2 são iguais`)
}


// Vai ser para comentários iniciais
//!>     Vai ser para comentários de alertas
//?>     Vai ser para comentários de melhorias
//>>     Vai ser para comentários de ajustes
//*>     Vai ser para comentários de aleatórios
